# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dc5573a66aca7a457cb932170f7a011d9809c0cc240dcad20bb43e36eb4f586ca0293b936205f5ae8ab0f52c77bd11eb8e7d06508c3afb41b1d14db2540ef6de

test:
  secret_key_base: ddc2cbbcf0b38b3927463fe74ab5f0c756b69202a99faf3c34a73e9b4548f171137002e217cade8178dde22bd7984947af1292b1fb51b02fc8755e3f68302ffa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
